# Copyright (c) 2024 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "OCI Landing Zones Orchestrator"
stackDescription: "Generic module that orchestrates Landing Zone configurations expressed in remote JSON or YAML files, that can reside in private OCI buckets, private GitHub repositories or in plain public URLs."
description: "Generic module that orchestrates Landing Zone configurations expressed in remote JSON or YAML files, that can reside in private OCI buckets, private GitHub repositories or in plain public URLs."
schemaVersion: 1.1.0
version: "2.0.1"
locale: "en"

# URL of CIS Landing Zone logo icon used on Application Information tab.
logoUrl: "https://objectstorage.us-ashburn-1.oraclecloud.com/p/taf6kC9fSJyQDNSYbxvqxS_JsdnSu56oFZ3-1h5vI7-WfJUv77mplChopLxZPePW/n/ociateam/b/cis-landing-zone/o/landing_zone_130.png"

variableGroups:
  - title: "Region"
    visible: true
    variables:
      - region

  - title: "Input Files"
    visible: true
    variables: 
      - configuration_source
      - oci_configuration_bucket
      - oci_configuration_objects
      - oci_dependency_objects
      - github_token
      - github_base_url
      - github_configuration_repo
      - github_configuration_branch
      - github_configuration_files
      - github_dependency_files
      - input_config_files_urls
      - url_dependency_source
      - url_dependency_source_oci_bucket
      - url_dependency_source_oci_objects
      - url_dependency_source_github_token
      - url_dependency_source_github_repo
      - url_dependency_source_github_branch
      - url_dependency_source_github_dependency_files

  - title: "Output Files"
    variables:
      - save_output
      - oci_object_prefix
      - github_file_prefix

  - title: "Hidden Variables"
    visible: false
    variables:
      - tenancy_ocid
      - user_ocid
      - fingerprint
      - private_key_path
      - private_key_password
      - region
    
variables:
  region:
    type: oci:identity:region:name
    title: "Region"
    description: "The region for deployment of regional resources. IAM resources (global) are always transparently deployed in the tenancy home region."
    required: true

  configuration_source:
    type: enum 
    title: "Configurations Source"
    description: "Select the source where configuration files are pulled from. Supported sources are OCI Object Storage buckets, GitHub repositories and URLs."
    required: true
    enum:
      - "ocibucket"
      - "github"
      - "url"
  
  oci_configuration_bucket:
    type: string
    title: "OCI Bucket Name"
    description : "The OCI Object Storage bucket name with Landing Zone configuration files. The executing user MUST have read permissions on the bucket."
    visible: 
      eq:
        - configuration_source
        - "ocibucket"
    
  oci_configuration_objects:
    type: array
    items:
      type: string
    multiline: true
    uniqueItems: true
    title: "Configuration Files"
    additionalProps:
        allowMultiple: true
    description: "The Landing Zone configuration files in OCI Object Storage bucket. Both JSON or YAML files are supported."
    visible: 
      eq:
        - configuration_source
        - "ocibucket"

  oci_dependency_objects:
    type: array
    items:
      type: string
    multiline: true
    uniqueItems: true
    title: "Dependency Files"
    additionalProps:
        allowMultiple: true
    description: "The dependency files in OCI Object Storage bucket required by the configuration files. Dependency files have their contents referred in the configuration files for enhanced automation. Only JSON files are supported."
    visible: 
      eq:
        - configuration_source
        - "ocibucket"  

  github_token:
    type: password
    title: "GitHub Token"
    description : "The token that allows working with the GitHub repository. Make sure you have a Personal Access Token (PAT) or Fine Grained Access Token (FGAT) in GitHub properly scoped to read (and write if you save the stack output back to GitHub) the repository."
    visible: 
      eq:
        - configuration_source
        - "github"

  github_base_url:
    type: string
    title: "Github Base URL"
    description: "Only required when working with GitHub Enterprise. The value must end with a slash. E.g. https://example.com/"
    visible:
      eq:
        - configuration_source
        - "github"
    
  github_configuration_repo:
    type: string
    title: "GitHub Repository"
    description : "The GitHub repository with Landing Zone configurations. A GitHub token with read permissions is required. Required format is organization/repository or user/repository"
    pattern: "^(.+\/.+)$|^$"
    visible: 
      eq:
        - configuration_source
        - "github"

  github_configuration_branch:
    type: string
    title: "GitHub Branch"
    description : "The GitHub branch with Landing Zone configurations. A GitHub token with read permissions is required." 
    visible: 
      eq:
        - configuration_source
        - "github"

  github_configuration_files:
    type: array
    items:
      type: string
    multiline: true
    uniqueItems: true
    title: "Configuration Files"
    additionalProps:
        allowMultiple: true
    description: "The Landing Zone configuration files in GitHub. Both JSON or YAML files are supported."
    visible: 
      eq:
        - configuration_source
        - "github"

  github_dependency_files:
    type: array
    items:
      type: string
    multiline: true
    uniqueItems: true
    title: "Dependency Files"
    additionalProps:
        allowMultiple: true
    description: "The dependency files in GitHub required by the configuration files. Dependency files have their contents referred in the configuration files for enhanced automation. Only JSON files are supported."
    visible: 
      eq:
        - configuration_source
        - "github"

  input_config_files_urls:
    type: array
    items:
      type: string
    multiline: true
    uniqueItems: true
    title: "Configuration Files"
    additionalProps:
        allowMultiple: true
    description: "The URLs to Landing Zone configuration files. Both JSON or YAML files are supported."
    visible: 
      eq:
        - configuration_source
        - "url"

  url_dependency_source:
    type: enum 
    title: "Dependencies Source for URL-based Configurations"
    description: "Select the source where dependency files required by the configuration files are pulled from. Supported sources are OCI Object Storage buckets and GitHub repositories."
    enum:
      - "none"
      - "ocibucket"
      - "github"
    visible: 
      eq:
        - configuration_source
        - "url"  
    
  url_dependency_source_oci_bucket:
    type: string
    title: "OCI Bucket Name"
    description : "The OCI Object Storage bucket name with dependency files required by the configuration files. The executing user MUST have read permissions on the bucket."
    visible: 
      and:
        - eq:
          - configuration_source
          - "url"
        - eq:
          - url_dependency_source
          - "ocibucket"

  url_dependency_source_oci_objects:
    type: array
    items:
      type: string
    multiline: true
    uniqueItems: true
    title: "Dependency Files"
    additionalProps:
      allowMultiple: true
    description: "The dependency files in OCI Object Storage bucket required by the configuration files. Dependency files have their contents referred in the configuration files for enhanced automation. Only JSON files are supported."
    required: false
    visible: 
      and:
        - eq:
          - configuration_source
          - "url"
        - eq:
          - url_dependency_source
          - "ocibucket"

  url_dependency_source_github_token:
    type: password
    title: "GitHub Token"
    description : "The token that allows working with the GitHub repository. Make sure you have a Personal Access Token (PAT) or Fine Grained Access Token (FGAT) in GitHub properly scoped to read (and write if you save the stack output back to GitHub) the repository."
    visible: 
      and:
        - eq:
          - configuration_source
          - "url"
        - eq:
          - url_dependency_source
          - "github"
    
  url_dependency_source_github_repo:
    type: string
    title: "GitHub Repository"
    description : "The GitHub repository with dependency files required by the configurations in the URLs. A GitHub token with read permissions is required."
    visible: 
      and:
        - eq:
          - configuration_source
          - "url"
        - eq:
          - url_dependency_source
          - "github"

  url_dependency_source_github_branch:
    type: string
    title: "GitHub Branch"
    description : "The GitHub branch with dependency files required by the configurations files. A GitHub token with read permissions is required."
    visible: 
      and:
        - eq:
          - configuration_source
          - "url"
        - eq:
          - url_dependency_source
          - "github" 

  url_dependency_source_github_dependency_files:
    type: array
    items:
      type: string
    multiline: true
    uniqueItems: true
    title: "Dependency Files"
    additionalProps:
        allowMultiple: true
    description: "The dependency files required by the configurations files. Dependency files have their contents referred in the configuration files for enhanced automation. Only JSON files are supported."
    visible: 
      and:
        - eq:
          - configuration_source
          - "url"
        - eq:
          - url_dependency_source
          - "github"   

  save_output:
    type: boolean
    title: "Save Output?"
    description: "Whether to save the stack output, that can be used as a dependency input on another stack. The output is saved in the same source defined above for the dependency files."
    visible: true

  oci_object_prefix:
    type: string
    title: "OCI Object Prefix"
    description : "The OCI object prefix. Use this to organize the output and avoid overwriting when you run multiple instances of this stack. A generated object name is appended to the provided prefix, like oci_object_prefix/object_name. The executing user must also have write permissions on the bucket."
    visible:
      and:
        - ${save_output}
        - or:
          - eq:
            - configuration_source
            - "ocibucket"  
          - eq:
            - url_dependency_source
            - "ocibucket"  
        
  github_file_prefix:
    type: string
    title: "GitHub File Prefix"
    description : "The GitHub file prefix. Use this to organize the output and avoid overwriting when you run multiple instances of this stack. A generated file name is appended to the provided prefix, like github_file_prefix/file_name. The GitHub token must also have write permissions on the repository."
    visible:
      and:
        - ${save_output}
        - or:
          - eq:
            - configuration_source
            - "github"  
          - eq:
            - url_dependency_source
            - "github" 
          
  # Hidden variables
  user_ocid:
    type: string

  fingerprint:
    type: string

  private_key_path:
    type: string

  private_key_password:
    type: password

outputs:
  region:
    type: string
    title: Region

  output_string:
    type: string
    title: Output Files 

outputGroups:
  - title: Environment
    outputs:
      - ${region}

  - title: Outputs 
    outputs:
      - ${output_string}
